function varargout=demo_pendulum_sym(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=3;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=3;
   return
  case 'directional_derivative'
   varargout{1}=1;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('demo_pendulum_sym_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});
end



function [out1,out2] = demo_pendulum_sym_rhs_1_0(x1,y1,x2,y2,a,b,tau,x1_d,y1_d,x2_d,y2_d,a_d,b_d,tau_d)
%DEMO_PENDULUM_SYM_RHS_1_0
%    [OUT1,OUT2] = DEMO_PENDULUM_SYM_RHS_1_0(X1,Y1,X2,Y2,A,B,TAU,X1_D,Y1_D,X2_D,Y2_D,A_D,B_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Feb-2025 13:26:37

out1 = y1;
if nargout > 1
    out2 = sin(x1)-cos(x1).*(a.*x2+b.*y2);
end
end


function [out1,out2] = demo_pendulum_sym_rhs_1_1(x1,y1,x2,y2,a,b,tau,x1_d,y1_d,x2_d,y2_d,a_d,b_d,tau_d)
%DEMO_PENDULUM_SYM_RHS_1_1
%    [OUT1,OUT2] = DEMO_PENDULUM_SYM_RHS_1_1(X1,Y1,X2,Y2,A,B,TAU,X1_D,Y1_D,X2_D,Y2_D,A_D,B_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Feb-2025 13:26:37

out1 = y1_d;
if nargout > 1
    t2 = cos(x1);
    out2 = -t2.*(a.*x2_d+a_d.*x2+b.*y2_d+b_d.*y2)+t2.*x1_d+x1_d.*sin(x1).*(a.*x2+b.*y2);
end
end


function [out1,out2] = demo_pendulum_sym_rhs_1_2(x1,y1,x2,y2,a,b,tau,x1_d,y1_d,x2_d,y2_d,a_d,b_d,tau_d)
%DEMO_PENDULUM_SYM_RHS_1_2
%    [OUT1,OUT2] = DEMO_PENDULUM_SYM_RHS_1_2(X1,Y1,X2,Y2,A,B,TAU,X1_D,Y1_D,X2_D,Y2_D,A_D,B_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Feb-2025 13:26:38

out1 = 0.0;
if nargout > 1
    t2 = cos(x1);
    t3 = sin(x1);
    t4 = x1_d.^2;
    out2 = -t3.*t4-t2.*(a_d.*x2_d.*2.0+b_d.*y2_d.*2.0)+t2.*t4.*(a.*x2+b.*y2)+t3.*x1_d.*(a.*x2_d+a_d.*x2+b.*y2_d+b_d.*y2).*2.0;
end
end


function [out1,out2] = demo_pendulum_sym_rhs_1_3(x1,y1,x2,y2,a,b,tau,x1_d,y1_d,x2_d,y2_d,a_d,b_d,tau_d)
%DEMO_PENDULUM_SYM_RHS_1_3
%    [OUT1,OUT2] = DEMO_PENDULUM_SYM_RHS_1_3(X1,Y1,X2,Y2,A,B,TAU,X1_D,Y1_D,X2_D,Y2_D,A_D,B_D,TAU_D)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-Feb-2025 13:26:38

out1 = 0.0;
if nargout > 1
    t2 = cos(x1);
    t3 = sin(x1);
    t4 = x1_d.^3;
    out2 = -t2.*t4-t3.*t4.*(a.*x2+b.*y2)+t3.*x1_d.*(a_d.*x2_d.*2.0+b_d.*y2_d.*2.0).*3.0+t2.*x1_d.^2.*(a.*x2_d+a_d.*x2+b.*y2_d+b_d.*y2).*3.0;
end
end

