function varargout=sym_cusp(action,varargin)
%% Automatically generated with matlabFunction
% 
%#ok<*DEFNU,*INUSD,*INUSL>

switch action
  case 'ntau'
   varargout{1}=1;
   return
  case 'npar'
   varargout{1}=6;
   return
  case 'tp_del'
   varargout{1}=0;
   return
  case 'maxorder'
   varargout{1}=5;
   return
  case 'directional_derivative'
   varargout{1}=0;
   return
end
ind=varargin{1};
order=varargin{2};
nout=varargin{3};
f=str2func(sprintf('sym_cusp_%s_%d_%d',action,ind,order));
varargout=cell(nout,1);
[varargout{:}]=f(varargin{4:end});




function [out1,out2] = sym_cusp_rhs_1_0(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6)
%SYM_CUSP_RHS_1_0
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_0(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Sep-2022 21:35:13

t2 = u1_2.*4.0;
t3 = -t2;
t4 = exp(t3);
t5 = t4+1.0;
t6 = 1.0./t5;
t7 = t6-1.0./2.0;
out1 = p4-u1_1+p1.*t7-p2.*u2_2;
if nargout > 1
    out2 = p5-u2_1+p3.*t7;
end


function [out1,out2] = sym_cusp_rhs_1_1(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d)
%SYM_CUSP_RHS_1_1
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_1(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Sep-2022 21:35:13

t2 = u1_2.*4.0;
t3 = -t2;
t4 = exp(t3);
t5 = t4+1.0;
t6 = 1.0./t5;
t7 = t6.^2;
t8 = t6-1.0./2.0;
out1 = p4_d-u1_1_d+p1_d.*t8-p2.*u2_2_d-p2_d.*u2_2+p1.*t4.*t7.*u1_2_d.*4.0;
if nargout > 1
    out2 = p5_d-u2_1_d+p3_d.*t8+p3.*t4.*t7.*u1_2_d.*4.0;
end


function [out1,out2] = sym_cusp_rhs_1_2(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d)
%SYM_CUSP_RHS_1_2
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_2(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Sep-2022 21:35:13

t2 = u1_2.*4.0;
t4 = u1_2.*8.0;
t3 = -t2;
t6 = -t4;
t5 = exp(t3);
t7 = exp(t6);
t8 = t5+1.0;
t9 = 1.0./t8.^2;
t10 = 1.0./t8.^3;
out1 = -p2_d.*u2_2_d_d-p2_d_d.*u2_2_d+p1_d.*t5.*t9.*u1_2_d_d.*4.0+p1_d_d.*t5.*t9.*u1_2_d.*4.0-p1.*t5.*t9.*u1_2_d.*u1_2_d_d.*1.6e+1+p1.*t7.*t10.*u1_2_d.*u1_2_d_d.*3.2e+1;
if nargout > 1
    out2 = p3_d.*t5.*t9.*u1_2_d_d.*4.0+p3_d_d.*t5.*t9.*u1_2_d.*4.0-p3.*t5.*t9.*u1_2_d.*u1_2_d_d.*1.6e+1+p3.*t7.*t10.*u1_2_d.*u1_2_d_d.*3.2e+1;
end


function [out1,out2] = sym_cusp_rhs_1_3(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,u1_1_d_d_d,u2_1_d_d_d,u1_2_d_d_d,u2_2_d_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d,p1_d_d_d,p2_d_d_d,p3_d_d_d,p4_d_d_d,p5_d_d_d,p6_d_d_d)
%SYM_CUSP_RHS_1_3
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_3(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,U1_1_D_D_D,U2_1_D_D_D,U1_2_D_D_D,U2_2_D_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D,P1_D_D_D,P2_D_D_D,P3_D_D_D,P4_D_D_D,P5_D_D_D,P6_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Sep-2022 21:35:14

t2 = u1_2.*4.0;
t4 = u1_2.*8.0;
t5 = u1_2.*1.2e+1;
t3 = -t2;
t7 = -t4;
t8 = -t5;
t6 = exp(t3);
t9 = exp(t7);
t10 = exp(t8);
t11 = t6+1.0;
t12 = 1.0./t11.^2;
t13 = 1.0./t11.^3;
t14 = t12.^2;
out1 = p1_d.*t6.*t12.*u1_2_d_d.*u1_2_d_d_d.*-1.6e+1-p1_d_d.*t6.*t12.*u1_2_d.*u1_2_d_d_d.*1.6e+1-p1_d_d_d.*t6.*t12.*u1_2_d.*u1_2_d_d.*1.6e+1+p1_d.*t9.*t13.*u1_2_d_d.*u1_2_d_d_d.*3.2e+1+p1_d_d.*t9.*t13.*u1_2_d.*u1_2_d_d_d.*3.2e+1+p1_d_d_d.*t9.*t13.*u1_2_d.*u1_2_d_d.*3.2e+1+p1.*t6.*t12.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e+1-p1.*t9.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2+p1.*t10.*t14.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2;
if nargout > 1
    out2 = p3_d.*t6.*t12.*u1_2_d_d.*u1_2_d_d_d.*-1.6e+1-p3_d_d.*t6.*t12.*u1_2_d.*u1_2_d_d_d.*1.6e+1-p3_d_d_d.*t6.*t12.*u1_2_d.*u1_2_d_d.*1.6e+1+p3_d.*t9.*t13.*u1_2_d_d.*u1_2_d_d_d.*3.2e+1+p3_d_d.*t9.*t13.*u1_2_d.*u1_2_d_d_d.*3.2e+1+p3_d_d_d.*t9.*t13.*u1_2_d.*u1_2_d_d.*3.2e+1+p3.*t6.*t12.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e+1-p3.*t9.*t13.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2+p3.*t10.*t14.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2;
end


function [out1,out2] = sym_cusp_rhs_1_4(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,u1_1_d_d_d,u2_1_d_d_d,u1_2_d_d_d,u2_2_d_d_d,u1_1_d_d_d_d,u2_1_d_d_d_d,u1_2_d_d_d_d,u2_2_d_d_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d,p1_d_d_d,p2_d_d_d,p3_d_d_d,p4_d_d_d,p5_d_d_d,p6_d_d_d,p1_d_d_d_d,p2_d_d_d_d,p3_d_d_d_d,p4_d_d_d_d,p5_d_d_d_d,p6_d_d_d_d)
%SYM_CUSP_RHS_1_4
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_4(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,U1_1_D_D_D,U2_1_D_D_D,U1_2_D_D_D,U2_2_D_D_D,U1_1_D_D_D_D,U2_1_D_D_D_D,U1_2_D_D_D_D,U2_2_D_D_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D,P1_D_D_D,P2_D_D_D,P3_D_D_D,P4_D_D_D,P5_D_D_D,P6_D_D_D,P1_D_D_D_D,P2_D_D_D_D,P3_D_D_D_D,P4_D_D_D_D,P5_D_D_D_D,P6_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Sep-2022 21:35:14

t2 = u1_2.*4.0;
t4 = u1_2.*8.0;
t5 = u1_2.*1.2e+1;
t6 = u1_2.*1.6e+1;
t3 = -t2;
t8 = -t4;
t9 = -t5;
t10 = -t6;
t7 = exp(t3);
t11 = exp(t8);
t12 = exp(t9);
t13 = exp(t10);
t14 = t7+1.0;
t15 = 1.0./t14.^2;
t16 = 1.0./t14.^3;
t18 = 1.0./t14.^5;
t17 = t15.^2;
out1 = p1_d.*t7.*t15.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e+1+p1_d_d.*t7.*t15.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e+1+p1_d_d_d.*t7.*t15.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*6.4e+1+p1_d_d_d_d.*t7.*t15.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e+1-p1_d.*t11.*t16.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2-p1_d_d.*t11.*t16.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2-p1_d_d_d.*t11.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e+2-p1_d_d_d_d.*t11.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2+p1_d.*t12.*t17.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2+p1_d_d.*t12.*t17.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2+p1_d_d_d.*t12.*t17.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e+2+p1_d_d_d_d.*t12.*t17.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2-p1.*t7.*t15.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e+2+p1.*t11.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e+3-p1.*t12.*t17.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e+3+p1.*t13.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e+3;
if nargout > 1
    out2 = p3_d.*t7.*t15.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e+1+p3_d_d.*t7.*t15.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.4e+1+p3_d_d_d.*t7.*t15.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*6.4e+1+p3_d_d_d_d.*t7.*t15.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*6.4e+1-p3_d.*t11.*t16.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2-p3_d_d.*t11.*t16.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2-p3_d_d_d.*t11.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e+2-p3_d_d_d_d.*t11.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2+p3_d.*t12.*t17.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2+p3_d_d.*t12.*t17.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.84e+2+p3_d_d_d.*t12.*t17.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*3.84e+2+p3_d_d_d_d.*t12.*t17.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*3.84e+2-p3.*t7.*t15.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e+2+p3.*t11.*t16.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e+3-p3.*t12.*t17.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e+3+p3.*t13.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e+3;
end


function [out1,out2] = sym_cusp_rhs_1_5(u1_1,u2_1,u1_2,u2_2,p1,p2,p3,p4,p5,p6,u1_1_d,u2_1_d,u1_2_d,u2_2_d,u1_1_d_d,u2_1_d_d,u1_2_d_d,u2_2_d_d,u1_1_d_d_d,u2_1_d_d_d,u1_2_d_d_d,u2_2_d_d_d,u1_1_d_d_d_d,u2_1_d_d_d_d,u1_2_d_d_d_d,u2_2_d_d_d_d,u1_1_d_d_d_d_d,u2_1_d_d_d_d_d,u1_2_d_d_d_d_d,u2_2_d_d_d_d_d,p1_d,p2_d,p3_d,p4_d,p5_d,p6_d,p1_d_d,p2_d_d,p3_d_d,p4_d_d,p5_d_d,p6_d_d,p1_d_d_d,p2_d_d_d,p3_d_d_d,p4_d_d_d,p5_d_d_d,p6_d_d_d,p1_d_d_d_d,p2_d_d_d_d,p3_d_d_d_d,p4_d_d_d_d,p5_d_d_d_d,p6_d_d_d_d,p1_d_d_d_d_d,p2_d_d_d_d_d,p3_d_d_d_d_d,p4_d_d_d_d_d,p5_d_d_d_d_d,p6_d_d_d_d_d)
%SYM_CUSP_RHS_1_5
%    [OUT1,OUT2] = SYM_CUSP_RHS_1_5(U1_1,U2_1,U1_2,U2_2,P1,P2,P3,P4,P5,P6,U1_1_D,U2_1_D,U1_2_D,U2_2_D,U1_1_D_D,U2_1_D_D,U1_2_D_D,U2_2_D_D,U1_1_D_D_D,U2_1_D_D_D,U1_2_D_D_D,U2_2_D_D_D,U1_1_D_D_D_D,U2_1_D_D_D_D,U1_2_D_D_D_D,U2_2_D_D_D_D,U1_1_D_D_D_D_D,U2_1_D_D_D_D_D,U1_2_D_D_D_D_D,U2_2_D_D_D_D_D,P1_D,P2_D,P3_D,P4_D,P5_D,P6_D,P1_D_D,P2_D_D,P3_D_D,P4_D_D,P5_D_D,P6_D_D,P1_D_D_D,P2_D_D_D,P3_D_D_D,P4_D_D_D,P5_D_D_D,P6_D_D_D,P1_D_D_D_D,P2_D_D_D_D,P3_D_D_D_D,P4_D_D_D_D,P5_D_D_D_D,P6_D_D_D_D,P1_D_D_D_D_D,P2_D_D_D_D_D,P3_D_D_D_D_D,P4_D_D_D_D_D,P5_D_D_D_D_D,P6_D_D_D_D_D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    29-Sep-2022 21:35:14

t2 = u1_2.*4.0;
t4 = u1_2.*8.0;
t5 = u1_2.*1.2e+1;
t6 = u1_2.*1.6e+1;
t7 = u1_2.*2.0e+1;
t3 = -t2;
t9 = -t4;
t10 = -t5;
t11 = -t6;
t12 = -t7;
t8 = exp(t3);
t13 = exp(t9);
t14 = exp(t10);
t15 = exp(t11);
t16 = exp(t12);
t17 = t8+1.0;
t18 = 1.0./t17.^2;
t19 = 1.0./t17.^3;
t21 = 1.0./t17.^5;
t20 = t18.^2;
t22 = t18.^3;
out1 = p1_d.*t8.*t18.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*-2.56e+2-p1_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e+2-p1_d_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e+2-p1_d_d_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*2.56e+2-p1_d_d_d_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e+2+p1_d.*t13.*t19.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p1_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p1_d_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p1_d_d_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p1_d_d_d_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e+3-p1_d.*t14.*t20.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p1_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p1_d_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p1_d_d_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p1_d_d_d_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e+3+p1_d.*t15.*t21.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p1_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p1_d_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p1_d_d_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p1_d_d_d_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e+3+p1.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.024e+3-p1.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.072e+4+p1.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.536e+5-p1.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.4576e+5+p1.*t16.*t22.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.2288e+5;
if nargout > 1
    out2 = p3_d.*t8.*t18.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*-2.56e+2-p3_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e+2-p3_d_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.56e+2-p3_d_d_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*2.56e+2-p3_d_d_d_d_d.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*2.56e+2+p3_d.*t13.*t19.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p3_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p3_d_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p3_d_d_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*3.584e+3+p3_d_d_d_d_d.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*3.584e+3-p3_d.*t14.*t20.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p3_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p3_d_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p3_d_d_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*9.216e+3-p3_d_d_d_d_d.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*9.216e+3+p3_d.*t15.*t21.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p3_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p3_d_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p3_d_d_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d_d.*6.144e+3+p3_d_d_d_d_d.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*6.144e+3+p3.*t8.*t18.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.024e+3-p3.*t13.*t19.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*3.072e+4+p3.*t14.*t20.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.536e+5-p3.*t15.*t21.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*2.4576e+5+p3.*t16.*t22.*u1_2_d.*u1_2_d_d.*u1_2_d_d_d.*u1_2_d_d_d_d.*u1_2_d_d_d_d_d.*1.2288e+5;
end

